version: '3.9'
services:
    openbooks:
        command: '--persist --name rickastley'
        image: 'evanbuss/openbooks:latest'
        volumes:
            - '/mnt/media/library/chaptarr-import'
        ports:
            - '8875:80'
