version: '3.9'
services:
    openbooks:
        command: '--persist --name qball_222'
        image: 'evanbuss/openbooks:latest'
        volumes:
            - '/mnt/user/media/library/chaptarr-import:/books'
        ports:
            - '8875:80'
        environment:
            - PUID=99
            - PGID=100
            - UMASK=000
            - TZ=America/New_York
